const fs = require('fs')

// function chooses licenses depending on user selection
const licenseText = (licenseUser, fullName) => {
  // license texts
  let MIT_userName = 'Copyright (c) [' + new Date().getFullYear() + '] [' + fullName + ']';
  let GNU_AGPLv3 = 
                  ['GNU AFFERO GENERAL PUBLIC LICENSE', 
                   'Version 3, 19 November 2007',
                   'Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>',
                   'Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.'
                  ];

  let MIT_License = 
                  ['MIT License', MIT_userName,
                  'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:',
                  'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.',
                  'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
                  ];
  let Boost_Software_License =
                  ['Boost Software License - Version 1.0 - August 17th, 2003',
                   'Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following:',
                   'The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.',
                   'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
                  ];
  let The_Unlicense = 
                  ['This is free and unencumbered software released into the public domain.',
                   'Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.',
                   'In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.',
                   'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'];

  // conditionals to select which license to choose
  if(licenseUser === "GNU AGPLv3"){
    return GNU_AGPLv3;
  }
  else if (licenseUser === "MIT"){
    return MIT_License;
  }
  else if (licenseUser === "Boost Software"){
    return Boost_Software_License;
  }
  else if (licenseUser === "The Unlicense"){
    return The_Unlicense;
  }
  
}

// function to generate markdown for README
module.exports = READMEdata => {
  // destructure
  const { fullName,
          gitUser,
          email,
          projTitle,
          projDescription,
          installInstruct,
          usageInfo,
          license,
          contribution,
          tests
      } = READMEdata;
  
  // select license
  const licenseTextString = licenseText(license, fullName);
  
  // README.md content
  return `# ${projTitle}
![licenseBadge](https://img.shields.io/badge/License-${license}-blue)

## Description
${projDescription}

## Table of Contents
* [Installation](#installation)
* [Usage](#usage)
* [Credits](#credits)
* [License](#license)

## Installation
${installInstruct}

## Usage
${usageInfo}

## License
![licenseBadge](https://img.shields.io/badge/License-${license}-blue)

${licenseTextString[0]}

${licenseTextString[1]}

${licenseTextString[2]}

${licenseTextString[3]}

## Contribution
${contribution}

## Test
${tests}

## Questions
Any questions? Contact at: ${email}

GitHub: [${gitUser}](https://github.com/${gitUser})`
}